from MultyPolynomial import MultyPolinomial
from ComplexMultyPolynomial import ComplexMultyPolynomial
from SinglePolynomial import SinglePolynomial
from ComplexSinglePolynomial import ComplexSinglePolynomial
